Adds xdg-desktop-portal to the submodule list
lxqt/lxqt pull request #2431
Opened 2023-05-26 11:14 UTC by luis-pereira

2023-07-23 20:19 UTC, stefonarch commented
Why is this not merged?

2023-07-24 03:49 UTC, tsujan commented
> Why is this not merged?

Perhaps it isn't tested yet?

2023-07-24 06:40 UTC, yan12125 requested changes
`CMakeLists.txt` should probably be updated as well

2023-07-24 06:40 UTC, yan12125 commented on .gitmodules
> +	url = ./xdg-desktop-portal-lxqt
```suggestion
	url = ../xdg-desktop-portal-lxqt
```

2023-07-26 13:20 UTC, yan12125 commented
Thanks for the update. I noticed a new branch https://github.com/lxqt/lxqt/tree/update-build, which seems related?

2023-07-26 18:00 UTC, luis-pereira commented
> Thanks for the update. I noticed a new branch https://github.com/lxqt/lxqt/tree/update-build, which seems related?

Thanks for the review. Yes, it's related. It updates the build system. PR here: https://github.com/lxqt/lxqt/pull/2455

2023-07-27 04:06 UTC, yan12125 approved these changes

2023-07-27 04:06 UTC, merged

2023-07-27 04:07 UTC, yan12125 commented
Thanks! I will look into the other PR.